[Python/design.md] Translation
Azure/azure-sdk-korean pull request #105
Opened 2022-08-03 15:49 UTC by wonhyeongseo

Currently in draft.
Closes https://github.com/Azure/azure-sdk-korean/issues/104

2022-08-05 12:07 UTC, yeongseon commented
[SHSongs](https://github.com/SHSongs) Could you please review this change? It would be appreciated if you review this change. :)

2022-08-05 13:47 UTC, SHSongs requested changes
문장을 조금 더 매끄럽게 변경하였습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
Yes No가 더 일반적으로 사용될 거 같습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
> +클라이언트 라이브러리의 API에 정말 많은 노력을 기울여야해요. 서비스의 첫인상이자 주로 쓰는 상호작용 방법이기 때문입니다.
"많은 노력을 기울여야합니다."가 자연스러운거 같습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
> +이 안내서는 HTTP 기반 요청/응답 구조를 염두에 두고 작성했지만, 아닌 서비스들에도 많은 부분을 적용하실 수 있습니다. 예로 들면 패키징과 네이밍, 도구와 프로젝트 구조를 비롯한 서비스들이 있어요.
"서비스들이 있습니다"가 자연스러운거 같습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
> +{% include requirement/MUST id="python-general-version-support" %} 파이썬 3.7 이상을 지원하고 있습니다.
"파이썬 2.7과 파이썬 3.5.3 이상을 지원하고 있습니다."로 변경 가능할거 같습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
> +서비스와 연결시키고 상호작용하는데 필요한 최소한의 전달인자만을 클라이언트 인스턴스를 생성할 때 요구해야합니다. 나머지 정보는 모두 선택적인 키워드 전달인자로 보내는 것이 바람직합니다.
"서비스와 연결하고 상호작용하는데 필요한 최소한의 인자를 클라이언트 인스턴스를 생성할 때 요구해야합니다." 가 더 자연스러울거 같습니다

2022-08-05 13:47 UTC, SHSongs commented on docs/python/design.md
> +예시로 의존관계인 외부 패키지가 모든 버전에 없기 때문에, 버전별로 서로 다른 외부 패키지에 의존해야만 하는 경우가 있습니다.
"예를들어, 파이썬2와 파이썬3가 다른 외부 패키지에 의존하고,  두 파이썬 버전이 같은 외부 의존 패키지를 사용할 수 없을 때 입니다."가 더 자연스러울 거 같습니다

2022-09-25 13:25 UTC, ianychoi commented
@wonhyeongseo is it still draft according to your side? Please double-check it thanks!

![image](https://user-images.githubusercontent.com/6965982/192145912-adbe6e0e-1694-4476-8215-a44b9b273a55.png)

2022-09-27 07:22 UTC, wonhyeongseo commented
I haven't worked on this for a while now, but if a partial improvement will suffice, I will turn the draft into a PR.

2022-10-05 07:05 UTC, ianychoi commented
@wonhyeongseo Thanks! Would you submit an issue regarding this so that others can follow-up?

2022-10-05 07:05 UTC, merged