Fix: title in GitHub Repos which already has been translated
Azure/azure-sdk-korean pull request #135
Opened 2023-07-27 15:44 UTC by FacerAin

### Request
There is a title that already has been translated in GitHub Repos but does not refelct (영문) delection in title.
Target: Guideline Contributions, Repository structure, Repository branching

### Related Issue
close #134

2023-07-29 04:40 UTC, ianychoi requested changes
Would you also translate the titles in Korean language? Thanks

2023-07-29 04:40 UTC, ianychoi commented on _data/sidebars/general_sidebar.yml
> -      - title: Guidelines Contributions (영문)
Please translate into Korean

2023-07-29 04:40 UTC, ianychoi commented on _data/sidebars/general_sidebar.yml
> +      - title: Repository structure
Please translate into Korean

2023-07-29 04:40 UTC, ianychoi commented on _data/sidebars/general_sidebar.yml
> +      - title: Repository branching
Please translate the title into Korean

2023-07-30 08:23 UTC, FacerAin commented
I also finished translating the title into korean you said. Thank you :)

2023-07-30 14:57 UTC, ianychoi commented
Looks good thank you

2023-07-30 14:57 UTC, merged