Translate README.md into KR
Azure/azure-sdk-korean pull request #141
Opened 2023-07-29 15:02 UTC by unki11

Translate README.md 기여하기 (Contributing) 부분 한글화

2023-07-30 15:02 UTC, ianychoi commented
Thank you for the PR but I can now say that this is intentional because README.md file can be seen also to non-Korean readers. Maybe for this, keeping both English and Korean parts would be better - would you revise it?

2023-08-03 00:43 UTC, unki11 commented
I think the same. thank you

2023-08-05 13:57 UTC, ianychoi requested changes
Thanks for your comment - would you reflect the changes?

2023-08-05 13:57 UTC, ianychoi commented on README.md
Then would you please add one more statement on this part like the below example?

`Note that below is Korean translation of contributing part on [Azure SDK's README.md](https://github.com/Azure/azure-sdk/blob/main/README.md#contributing).`
`아래는 [Azure SDK 저장소에 언급된 기여하기 파트](https://github.com/Azure/azure-sdk/blob/main/README.md#contributing)를 한글로 번역한 것입니다. 참고하셨으면 합니다.`

2023-08-05 13:57 UTC, ianychoi commented on README.md
> +이 프로젝트는 기여 및 제안을 환영합니다. 대부분의 기여는 귀하가 기여를 사용할 권리를 가지고 있으며 실제로 그러한 권리를 당사에 부여한다고 선언하는 기부자 라이센스 계약(CLA)에 동의하기를 요구합니다. 자세한 내용은 https://cla.microsoft.com 을 방문하시면 됩니다.
Please use a better word than "귀하".

2023-08-05 13:57 UTC, ianychoi commented on README.md
> +이 프로젝트는 기여 및 제안을 환영합니다. 대부분의 기여는 귀하가 기여를 사용할 권리를 가지고 있으며 실제로 그러한 권리를 당사에 부여한다고 선언하는 기부자 라이센스 계약(CLA)에 동의하기를 요구합니다. 자세한 내용은 https://cla.microsoft.com 을 방문하시면 됩니다.
Also translation of contributions and contributor needs to be concise - so, please change "기부자".

2023-08-05 13:57 UTC, ianychoi commented on README.md
> +pull request를 제출하면 CLA 봇이 자동으로 CLA를 제공하고 PR을 적절하게 꾸밀 필요가 있는지 여부를 결정합니다(예: 레이블, 댓글). 봇이 제공하는 지침을 따르면 됩니다. 이 작업은 CLA를 사용하여 모든 저장소에서 한 번만 수행하면 됩니다.
In English, first character is usually be capitalized. So, please change "pull" to "Pull".

2023-08-07 06:53 UTC, unki11 commented
@microsoft-github-policy-service agree

2023-08-07 07:03 UTC, unki11 commented
@ianychoi 리뷰 감사합니다. 모든 수정사항 반영했습니다.

2023-08-08 19:56 UTC, ianychoi commented
> Author

Almost done! I see that this comment has not been addressed - would you double-check?

"Also translation of contributions and contributor needs to be concise - so, please change "기부자"."

2023-08-09 01:28 UTC, unki11 commented on README.md
> +이 프로젝트는 기여 및 제안을 환영합니다. 대부분의 기여는 기부자가 기여를 사용할 권리를 가지고 있으며 실제로 그러한 권리를 당사에 부여한다고 선언하는 기부자 라이센스 계약(CLA)에 동의하기를 요구합니다. 자세한 내용은 https://cla.microsoft.com 을 방문하시면 됩니다.
Thanks for your review, but it seems to me that it has changed. please check it?

2023-08-09 02:42 UTC, ianychoi commented on README.md
> +이 프로젝트는 기여 및 제안을 환영합니다. 대부분의 기여는 기부자가 기여를 사용할 권리를 가지고 있으며 실제로 그러한 권리를 당사에 부여한다고 선언하는 기부자 라이센스 계약(CLA)에 동의하기를 요구합니다. 자세한 내용은 https://cla.microsoft.com 을 방문하시면 됩니다.
Please be consistent: 기여 & 기부자

2023-08-10 01:53 UTC, unki11 commented on README.md
> +이 프로젝트는 기여 및 제안을 환영합니다. 대부분의 기여는 기여자가 기여를 사용할 권리를 가지고 있으며 실제로 그러한 권리를 당사에 부여한다고 선언하는 기여자 라이센스 계약(CLA)에 동의하기를 요구합니다. 자세한 내용은 https://cla.microsoft.com 을 방문하시면 됩니다.
수정 완료했습니다. 친절하게 설명해주셔서 감사합니다.

2023-08-25 11:25 UTC, ianychoi commented
Thank you! Approving now

2023-08-25 11:25 UTC, merged