Translate : docs/general/implementation.md
Azure/azure-sdk-korean pull request #154
Opened 2023-08-09 09:11 UTC by neoseurae12

Related issue: #153

Let's get it done 🔥

2023-08-11 08:32 UTC, neoseurae12 commented on docs/general/implementation.md
>  분산 추적 메커니즘은 소비자가 프론트엔드에서 백엔드까지 코드를 추적할 수 있도록 합니다. 분산 추적 라이브러리는 고유한 작업 단위인 스팬(span)을 생성합니다.  각 스팬은 부모-자식 관계에 있습니다. 코드의 계층 구조가 깊어질수록 더 많은 스팬이 생성됩니다. 이후에 이러한 스팬은 필요에 따라 적절한 수신기로 내보내질 수 있습니다. 스팬을 추적하기 위해
"These spans can then be exported to a suitable receiver as needed."에서,
여기서 'receiver'(수신기)란 무엇인가? 그 예시에 어떤 것들이 있는가?

2023-08-11 08:36 UTC, neoseurae12 commented
Now you can see 'General Guidelines: Implementation' ALL in Korean. 😁

'General Guidelines: Implementation'의 번역을 완료했습니다. 이제 모두 한국어로 읽어보실 수 있습니다 😁

2023-08-24 23:39 UTC, ianychoi requested changes

2023-08-24 23:39 UTC, ianychoi commented on docs/general/implementation.md
>  분산 추적 메커니즘은 소비자가 프론트엔드에서 백엔드까지 코드를 추적할 수 있도록 합니다. 분산 추적 라이브러리는 고유한 작업 단위인 스팬(span)을 생성합니다.  각 스팬은 부모-자식 관계에 있습니다. 코드의 계층 구조가 깊어질수록 더 많은 스팬이 생성됩니다. 이후에 이러한 스팬은 필요에 따라 적절한 수신기로 내보내질 수 있습니다. 스팬을 추적하기 위해
I think you can find more details on distributed tracing and receivers on https://learn.microsoft.com/ko-kr/dotnet/core/diagnostics/distributed-tracing-concepts

2023-08-24 23:39 UTC, ianychoi commented on _data/sidebars/general_sidebar.yml
> +      - title: 구현 (번역 중)
Would you remove "(번역 중)" since you mention that you finished translating this part? Thanks!

2023-08-28 08:04 UTC, neoseurae12 commented on _data/sidebars/general_sidebar.yml
> +      - title: 구현 (번역 중)
Oh thanks for your reviewing. can you check this out once again? Thanks :)

2023-08-28 11:34 UTC, merged