[Suggestion] Update reviewprocess docs for reflect eng docs changes
Azure/azure-sdk-korean pull request #156
Opened 2023-08-12 05:12 UTC by FacerAin

### Requests
- https://github.com/Azure/azure-sdk/commit/c03f8f2c268e3bcabdef2d36b655872dfe2c7a70 There are some changes in eng review_process docs which add tables and sentences.
- For readability, I would like to incorporate their changes into the Korean docs.

kor: https://azure.github.io/azure-sdk-korean/policies_reviewprocess.html
eng: https://azure.github.io/azure-sdk/policies_reviewprocess.html

### Related Issue
close: #150

2023-08-12 05:15 UTC, FacerAin commented on docs/policies/reviewprocess.md
> +| REST API 스펙 | 권장 | [azure/azure-rest-api-specs-pr](https://github.com/azure/azure-rest-api-specs-pr) 또는 [azure/azure-rest-api-specs](https://github.com/azure/azure-rest-api-specs) 저장소의 검토된 REST API
https://github.com/azure/azure-rest-api-specs-pr
I am unable to access the link provided above. Is it a private repository for an internal team, or is the link invalid?

2023-08-12 05:17 UTC, FacerAin commented
> @microsoft-github-policy-service agree [company="{your company}"]

@microsoft-github-policy-service agree [company="{Kyunghee University}"]

2023-08-12 05:18 UTC, FacerAin commented
> @FacerAin please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2023-08-12 05:21 UTC, FacerAin commented
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

2023-08-24 23:36 UTC, ianychoi requested changes
Great - would you reflect the change?

2023-08-24 23:36 UTC, ianychoi commented on docs/policies/reviewprocess.md
> +| REST API 스펙 | 권장 | [azure/azure-rest-api-specs-pr](https://github.com/azure/azure-rest-api-specs-pr) 또는 [azure/azure-rest-api-specs](https://github.com/azure/azure-rest-api-specs) 저장소의 검토된 REST API
Thank you - how about mentioning like `[azure/azure-rest-api-specs-pr (직원 액세스)](https://github.com/azure/azure-rest-api-specs-pr)` (source: https://github.com/Azure/azure-rest-api-specs/wiki )?

2023-08-28 05:53 UTC, FacerAin commented
@ianychoi 
I reflected the change you mentioned. Thank you for review☺️

2023-08-28 11:49 UTC, merged